version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
    pre_build:
        commands:
            - yum install -y yum-utils
            - yum-builddep -y python3
            - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
            - yum -y install terraform
    build:
        commands:
            - echo "build starting stage"
            - cd terraform
            - terraform init
            #- terraform destroy -var-file=dev_env_tf_scripts.tfvars -auto-approve
            - terraform apply -var-file=dev_env_tf_scripts.tfvars -auto-approve
            
    
        
        
